/** This code was generated by AI */
import logoPng from '../assets/logo.png'
import './Footer.css'

const footerNavItems = ['About', 'Venues', 'Request', 'Privacy']
const socialItems = ['f', 'tg', 'ig', 'be']

function Footer() {
    return (
        <footer className="site-footer">
            <div className="site-footer__content">
                <section className="site-footer__brand-column" aria-label="Footer branding">
                    <img className="site-footer__logo" src={logoPng} alt="SEA Access logo" />

                    <div className="site-footer__contact-block">
                        <h3>Contact Us</h3>

                        <div className="site-footer__contact-item">
                            <span className="site-footer__icon" aria-hidden="true">
                                o
                            </span>
                            <span>Address</span>
                        </div>

                        <div className="site-footer__contact-item">
                            <span className="site-footer__icon" aria-hidden="true">
                                []
                            </span>
                            <span>livialzg@uw.edu</span>
                        </div>
                    </div>
                </section>

                <section className="site-footer__nav-column" aria-label="Footer navigation">
                    {footerNavItems.map((item) => (
                        <button key={item} className="site-footer__text-button" type="button">
                            {item}
                        </button>
                    ))}
                </section>

                <section className="site-footer__subscribe-column" aria-label="Subscribe section">
                    <h3>Subscribe</h3>

                    <form className="site-footer__subscribe-form" onSubmit={(event) => event.preventDefault()}>
                        <input
                            className="site-footer__input"
                            type="email"
                            placeholder="Email"
                            aria-label="Email"
                        />
                        <button className="site-footer__subscribe-button" type="submit">
                            Subscribe
                        </button>
                    </form>

                    <div className="site-footer__social-wrap">
                        <span className="site-footer__follow-label">Follow Us</span>

                        <div className="site-footer__social-list" aria-label="Social links">
                            {socialItems.map((item) => (
                                <button key={item} className="site-footer__social-button" type="button">
                                    {item}
                                </button>
                            ))}
                        </div>
                    </div>
                </section>
            </div>

            <div className="site-footer__bottom-row">
                <button className="site-footer__legal-button" type="button">
                    Privacy Policy
                </button>
                <button className="site-footer__legal-button" type="button">
                    Terms of Use
                </button>
            </div>
        </footer>
    )
}

export default Footer