/** mostly generated by AI  */
import { NavLink } from 'react-router-dom'
import logoPng from '../assets/logo.png'
import './Header.css'

function Header({ logoSrc = logoPng, logoAlt = 'SEA Access logo', navItems = [] }) {
    return (
        <header className="site-header">
            <div className="site-header__branding">
                <NavLink className="site-header__logo-link" to="/" aria-label="SEA Access home">
                    {logoSrc ? (
                        <img className="site-header__logo-image" src={logoSrc} alt={logoAlt} />
                    ) : (
                        <span className="site-header__logo-fallback">SEA Access</span>
                    )}
                </NavLink>
            </div>

            <nav className="site-header__nav" aria-label="Primary">
                {navItems.map((item) => (
                    <NavLink
                        key={item.label}
                        to={item.href}
                        className={({ isActive }) =>
                            isActive ? 'site-header__nav-link site-header__nav-link--active' : 'site-header__nav-link'
                        }
                    >
                        {item.label}
                    </NavLink>
                ))}
            </nav>
        </header>
    )
}

export default Header