/** mostly generated by AI  */
import { useEffect, useState } from 'react'
import { NavLink, useNavigate } from 'react-router-dom'
import { onAuthStateChanged } from 'firebase/auth'
import { auth } from '../firebase'
import logoPng from '../assets/logo.png'
import './Header.css'
import { UserCircle } from 'lucide-react'

function Header({ logoSrc = logoPng, logoAlt = 'SEA Access logo', navItems = [] }) {
    const navigate = useNavigate()
    const [user, setUser] = useState(null)
    const [authLoading, setAuthLoading] = useState(true)

    useEffect(() => {
        const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
            setUser(currentUser)
            setAuthLoading(false)
        })
        return unsubscribe
    }, [])

    return (
        <header className="site-header">
            <div className="site-header__branding">
                <NavLink className="site-header__logo-link" to="/" aria-label="SEA Access home">
                    {logoSrc ? (
                        <img className="site-header__logo-image" src={logoSrc} alt={logoAlt} />
                    ) : (
                        <span className="site-header__logo-fallback">SEA Access</span>
                    )}
                </NavLink>
            </div>

            <div className="site-header__right">
                <nav className="site-header__nav" aria-label="Primary">
                    {navItems.map((item) => (
                        <NavLink
                            key={item.label}
                            to={item.href}
                            className={({ isActive }) =>
                                isActive ? 'site-header__nav-link site-header__nav-link--active' : 'site-header__nav-link'
                            }
                        >
                            {item.label}
                        </NavLink>
                    ))}
                </nav>

                <div className="site-header__auth">
                    {authLoading ? null : user ? (
                        <button
                            className="site-header__icon-btn"
                            type="button"
                            onClick={() => navigate('/profile')}
                            aria-label="Profile"
                        >
                            <UserCircle size={28} stroke="#4543C6" />
                        </button>
                    ) : (
                        <button
                            className="btn-solid"
                            type="button"
                            onClick={() => navigate('/signin')}
                        >
                            Sign In
                        </button>
                    )}
                </div>
            </div>
        </header>
    )
}

export default Header
