/** mostly generated by AI  */
import logoPng from '../assets/logo.png'
import './Header.css'

function Header({ logoSrc = logoPng, logoAlt = 'SEA Access logo', navItems = [] }) {
    return (
        <header className="site-header">
            <div className="site-header__branding">
                <a className="site-header__logo-link" href="#" aria-label="SEA Access home">
                    {logoSrc ? (
                        <img className="site-header__logo-image" src={logoSrc} alt={logoAlt} />
                    ) : (
                        <span className="site-header__logo-fallback">SEA Access</span>
                    )}
                </a>
            </div>

            <nav className="site-header__nav" aria-label="Primary">
                {navItems.map((item) => (
                    <a key={item.label} href={item.href}>
                        {item.label}
                    </a>
                ))}
            </nav>
        </header>
    )
}

export default Header