/** This code was generated by AI */

/** Dummy starting page, this code can be nuked entirely but rn it's just a
 * button to get to the filter page.
 */
import { useState } from 'react'
import FilterPage from './filter'
import ReviewForm from './components/ReviewForm'
import ExplorePage from './explore'
import HomePage from './home'
import VenuePage from './venue'
import './App.css'

function App() {
  const [isFilterPageOpen, setIsFilterPageOpen] = useState(false)
  const [isExplorePageOpen, setIsExplorePageOpen] = useState(false)
  const [isReviewOpen, setIsReviewOpen] = useState(false)
  const [isHomePageOpen, setIsHomePageOpen] = useState(false)
  const [isVenuePageOpen, setIsVenuePageOpen] = useState(false)

  if (isFilterPageOpen) {
    return <FilterPage onBack={() => setIsFilterPageOpen(false)} />
  }

  if (isExplorePageOpen) {
    return <ExplorePage />
  }

  if (isHomePageOpen) {
    return <HomePage />
  }

  if (isVenuePageOpen) {
    return <VenuePage onBack={() => setIsVenuePageOpen(false)} />
  }

  return (
    <main className="app-shell">
      <header className="starter-header">
        <button
          className="test-filter-button"
          type="button"
          onClick={() => setIsFilterPageOpen(true)}
        >
          Test Filter
        </button>

        <button
          className="test-filter-button"
          type="button"
          onClick={() => setIsExplorePageOpen(true)}
        >
          Test Explore
        </button>

        <button
          className="test-review-button"
          type="button"
          onClick={() => setIsReviewOpen(true)}
        >
          Write Review
        </button>

        <button
          className="test-review-button"
          type="button"
          onClick={() => setIsHomePageOpen(true)}
        >
          Home Page
        </button>

        <button
          className="test-review-button"
          type="button"
          onClick={() => setIsVenuePageOpen(true)}
        >
          Venue Page
        </button>
      </header>

      <ReviewForm isOpen={isReviewOpen} onClose={() => setIsReviewOpen(false)} />
    </main>
  )
}

export default App
