/** This code was generated by AI */

/** Dummy starting page, this code can be nuked entirely but rn it's just a
 * button to get to the filter page.
 */
import { useState } from 'react'
import FilterPage from './filter'
import './App.css'

function App() {
  const [isFilterPageOpen, setIsFilterPageOpen] = useState(false)

  if (isFilterPageOpen) {
    return <FilterPage onBack={() => setIsFilterPageOpen(false)} />
  }

  return (
    <main className="app-shell">
      <header className="starter-header">
        <button
          className="test-filter-button"
          type="button"
          onClick={() => setIsFilterPageOpen(true)}
        >
          Test Filter
        </button>
      </header>
    </main>
  )
}

export default App
