/** Explore page, mostly (70%) generated by AI  */
import { useState } from "react";
import Header from "./components/Header";
import Footer from "./components/Footer";
import filterSectionsText from './data/filter-sections/access-filters.txt?raw'
//import VenueRequestPopup from "./VenueRequestPopup";
import "./explore.css";

// for header 
const navItems = [
    { label: 'Explore', href: '#' },
    { label: 'About', href: '#' },
    { label: 'Request', href: '#' },
]

const sampleVenues = [
    {
        id: 1,
        name: "Paramount Theatre",
        address: "123 Street Name Address",
        rating: 4.2,
        image:
            "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=1200&auto=format&fit=crop",
    },
    {
        id: 2,
        name: "Lumen Field",
        address: "123 Street Name Address",
        rating: 4.2,
        image:
            "https://images.unsplash.com/photo-1547347298-4074fc3086f0?q=80&w=1200&auto=format&fit=crop",
    },
    {
        id: 3,
        name: "WaMu Theater",
        address: "123 Street Name Address",
        rating: 4.2,
        image:
            "https://images.unsplash.com/photo-1516280440614-37939bbacd81?q=80&w=1200&auto=format&fit=crop",
    },
    {
        id: 4,
        name: "The Crocodile",
        address: "123 Street Name Address",
        rating: 4.2,
        image:
            "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?q=80&w=1200&auto=format&fit=crop",
    },
];

/** 
const sidebarFilters = [
    {
        heading: "Reviews Tagged",
        items: ["Blind/Visual Impairment", "Wheelchair", "Hearing"],
    },
    {
        heading: "Parking & Transport",
        items: ["On-Site Parking", "Nearby Pickup/Dropoff"],
    },
    {
        heading: "Accessible Bathrooms",
        items: ["Dedicated ADA Bathrooms", "Grab Bar", "Emergency Cord"],
    },
    {
        heading: "In-Venue Accessibility",
        items: ["Elevator", "Sensory Room", "ADA Seating", "Step-Free"],
    },
    {
        heading: "Staff",
        items: ["Helpful Staff", "ADA Staff", "Clear Communication"],
    },
];
*/

// filter for parsing the txt file that contains all filter options 
function parseFilterSection(sectionText) {
    const [title, ...items] = sectionText
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)

    return { title, items }
}
const filterSections = filterSectionsText
    .split(/\n\s*\n/)
    .map((section) => section.trim())
    .filter(Boolean)
    .map(parseFilterSection)

export default function Explore() {
    const [searchInput, setSearchInput] = useState("");
    const [sortBy, setSortBy] = useState("ratings");
    const [showPopup, setShowPopup] = useState(false);

    // AI-assisted starter logic for search/filtering, then edited into this version
    let shownVenues = sampleVenues.filter((venue) =>
        venue.name.toLowerCase().includes(searchInput.toLowerCase())
    );

    if (sortBy === "name") {
        shownVenues = [...shownVenues].sort((a, b) => a.name.localeCompare(b.name));
    } else if (sortBy === "ratings") {
        shownVenues = [...shownVenues].sort((a, b) => b.rating - a.rating);
    }

    return (
        <div className="explore-page">
            <Header navItems={navItems} />

            <main className="explore-content">
                <p className="back-link">← Back To Home</p>

                <div className="search-sort-row">
                    <input
                        type="text"
                        className="search-bar"
                        placeholder="Search venues and categories..."
                        value={searchInput}
                        onChange={(event) => setSearchInput(event.target.value)}
                    />

                    <select
                        className="sort-dropdown"
                        value={sortBy}
                        onChange={(event) => setSortBy(event.target.value)}
                    >
                        <option value="ratings">Sort by Ratings</option>
                        <option value="name">Sort by Name</option>
                    </select>

                    {/* AI-assisted starter state wiring for opening the request popup */}
                    <button
                        className="request-button"
                        onClick={() => setShowPopup(true)}
                    >
                        Request Venue
                    </button>
                </div>

                <div className="results-header">
                    <h1>Showing results for “{searchInput || "Search Input"}”</h1>
                    <p>Showing {shownVenues.length} results</p>
                </div>

                <div className="results-layout">
                    <aside className="filter-sidebar">
                        {filterSections.map((section) => (
                            <div key={section.title} className="filter-group">
                                <h3>{section.title}</h3>

                                <div className="tag-list">
                                    {section.items.map((item) => (
                                        <button key={item} className="tag-button">
                                            {item} +
                                        </button>
                                    ))}
                                </div>
                            </div>
                        ))}

                    </aside>

                    <section className="venue-results">
                        {shownVenues.map((venue) => (
                            <div key={venue.id} className="venue-card">
                                <img
                                    src={venue.image}
                                    alt={venue.name}
                                    className="venue-image"
                                />

                                <div className="venue-info">
                                    <div className="venue-top-row">
                                        <h2>{venue.name}</h2>
                                        <span className="venue-rating">☆ {venue.rating}</span>
                                    </div>

                                    <p className="venue-address">{venue.address}</p>
                                    <button className="overview-button">
                                        Accessibility Overview ˅
                                    </button>
                                </div>
                            </div>
                        ))}
                    </section>
                </div>
            </main>

            <Footer />

            {showPopup && (
                <VenueRequestPopup onClose={() => setShowPopup(false)} />
            )}
        </div>
    );
}