/** Explore page, mostly (70%) generated by AI  */
import { useState } from "react";
import { useNavigate, useSearchParams } from 'react-router-dom'
import Header from "./components/Header";
import Footer from "./components/Footer";
import filterSectionsText from './data/filter-sections/access-filters.txt?raw'
import { venues } from './data/venues'
import { getFilters, saveFilters } from "./utils/filterStorage"
import "./explore.css";

// for header 
const navItems = [
    { label: 'Explore', href: '/explore' },
    { label: 'About', href: '#' },
    { label: 'Request', href: '#' },
]

/** 
const sidebarFilters = [
    {
        heading: "Reviews Tagged",
        items: ["Blind/Visual Impairment", "Wheelchair", "Hearing"],
    },
    {
        heading: "Parking & Transport",
        items: ["On-Site Parking", "Nearby Pickup/Dropoff"],
    },
    {
        heading: "Accessible Bathrooms",
        items: ["Dedicated ADA Bathrooms", "Grab Bar", "Emergency Cord"],
    },
    {
        heading: "In-Venue Accessibility",
        items: ["Elevator", "Sensory Room", "ADA Seating", "Step-Free"],
    },
    {
        heading: "Staff",
        items: ["Helpful Staff", "ADA Staff", "Clear Communication"],
    },
];
*/

// filter for parsing the txt file that contains all filter options 
function parseFilterSection(sectionText) {
    const [title, ...items] = sectionText
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)

    return { title, items }
}
const filterSections = filterSectionsText
    .split(/\n\s*\n/)
    .map((section) => section.trim())
    .filter(Boolean)
    .map(parseFilterSection)

export default function Explore() {
    const navigate = useNavigate()
    const [searchParams] = useSearchParams()
    const [searchInput, setSearchInput] = useState(searchParams.get("q") || "")
    const [sortBy, setSortBy] = useState("ratings");
    // AI-assisted: starter logic for matching search text against venue names and helper tags
    const normalizedSearch = searchInput.trim().toLowerCase()
    const [selectedFilters, setSelectedFilters] = useState(getFilters)

    const toggleFilter = (item) => {
        setSelectedFilters((prev) => {
            const updated = prev.includes(item)
                ? prev.filter((f) => f !== item)
                : [...prev, item]
            saveFilters(updated)
            return updated
        })
    }

    let shownVenues = venues.filter((venue) => {
        const nameMatches = venue.name.toLowerCase().includes(normalizedSearch)

        const tagMatches = venue.searchTags?.some((tag) =>
            tag.toLowerCase().includes(normalizedSearch)
        )

        return normalizedSearch === "" || nameMatches || tagMatches
    })

    // AI-assisted: combines text search results with the selected accessibility filter
    if (selectedFilters.length > 0) {
        shownVenues = shownVenues.filter((venue) =>
            selectedFilters.every((f) => venue.accessibilityTags?.includes(f))
        )
    }

    if (sortBy === "name") {
        shownVenues = [...shownVenues].sort((a, b) => a.name.localeCompare(b.name))
    } else if (sortBy === "ratings") {
        shownVenues = [...shownVenues].sort((a, b) => b.rating - a.rating)
    }

    return (
        <div className="explore-page">
            <Header navItems={navItems} />

            <main className="explore-content">
                <button className="back-link" type="button" onClick={() => navigate('/')}>
                    ← Back To Home
                </button>

                <div className="search-sort-row">
                    <input
                        type="text"
                        className="search-bar"
                        placeholder="Search venues and categories..."
                        value={searchInput}
                        onChange={(event) => setSearchInput(event.target.value)}
                    />

                    <select
                        className="sort-dropdown"
                        value={sortBy}
                        onChange={(event) => setSortBy(event.target.value)}
                    >
                        <option value="ratings">Sort by Ratings</option>
                        <option value="name">Sort by Name</option>
                    </select>

                    <button
                        className="filter-button"
                        type="button"
                        onClick={() => navigate('/explore/filter')}
                    >
                        Filter
                    </button>

                    <button
                        className="request-button"
                        type="button"
                    >
                        Request Venue
                    </button>
                </div>

                <div className="results-header">
                    <h1>Showing results for "{searchInput || "Search Input"}"</h1>
                    <p>Showing {shownVenues.length} results</p>
                    {selectedFilters.length > 0 && <p>Active filters: {selectedFilters.join(", ")}</p>}
                </div>

                <div className="results-layout">
                    <aside className="filter-sidebar">
                        {filterSections.map((section) => (
                            <div key={section.title} className="filter-group">
                                <h3>{section.title}</h3>

                                <div className="tag-list">
                                    {section.items.map((item) => (
                                        <button
                                            key={item}
                                            type="button"
                                            className={`tag-button ${selectedFilters.includes(item) ? "tag-button--active" : ""}`}
                                            aria-pressed={selectedFilters.includes(item)}
                                            onClick={() => toggleFilter(item)}
                                        >
                                            {item} {selectedFilters.includes(item) ? "✓" : "+"}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        ))}

                    </aside>

                    <section className="venue-results">
                        {shownVenues.map((venue) => (
                            <article
                                key={venue.id}
                                className="venue-card"
                                onClick={() => navigate(`/venues/${venue.id}`)}
                                onKeyDown={(event) => {
                                    if (event.key === 'Enter' || event.key === ' ') {
                                        event.preventDefault()
                                        navigate(`/venues/${venue.id}`)
                                    }
                                }}
                                role="button"
                                tabIndex={0}
                            >
                                <img
                                    src={venue.image}
                                    alt={venue.name}
                                    className="venue-image"
                                />

                                <div className="venue-info">
                                    <div className="venue-top-row">
                                        <h2>{venue.name}</h2>
                                        <span className="venue-rating">☆ {venue.rating}</span>
                                    </div>

                                    <p className="venue-address">{venue.address}</p>
                                    <button
                                        className="overview-button"
                                        type="button"
                                        onClick={() => navigate(`/venues/${venue.id}`)}
                                    >
                                        Accessibility Overview ˅
                                    </button>
                                </div>
                            </article>
                        ))}
                    </section>
                </div>
            </main>

            <Footer />
        </div>
    );
}