/** Filter page, mostly generated by AI  */
import { useNavigate } from 'react-router-dom'
import Footer from './components/Footer'
import Header from './components/Header'
import filterSectionsText from './data/filter-sections/access-filters.txt?raw'
import { getFilters, saveFilters, clearFilters } from "./utils/filterStorage"
import { useState } from 'react'
import './filter.css'

// for header 
const navItems = [
    { label: 'Explore', href: '/explore' },
    { label: 'About', href: '#' },
    { label: 'Request', href: '#' },
]

// filter for parsing the txt file that contains all filter options 
function parseFilterSection(sectionText) {
    const [title, ...items] = sectionText
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)

    return { title, items }
}
const filterSections = filterSectionsText
    .split(/\n\s*\n/)
    .map((section) => section.trim())
    .filter(Boolean)
    .map(parseFilterSection)

function FilterPage() {
    const navigate = useNavigate()
    const [selectedFilters, setSelectedFilters] = useState(getFilters)

    const toggleFilter = (item) => {
        setSelectedFilters((prev) => {
            const updated = prev.includes(item)
                ? prev.filter((f) => f !== item)
                : [...prev, item]
            saveFilters(updated)
            return updated
        })
    }

    const handleClearAll = () => {
        clearFilters()
        setSelectedFilters([])
    }

    return (
        <div className="filter-page ui-page">
            <Header navItems={navItems} />

            <main className="filter-content ui-container">
                <button className="back-link" type="button" onClick={() => navigate(-1)}>
                    <span aria-hidden="true">&lt;</span>
                    <span>Back To Search</span>
                </button>

                <div className="filter-page__top-row">
                    <h1>Filter by Access Needs</h1>

                    <button className="ghost-action ui-pill-button ui-pill-button--ghost" type="button" onClick={handleClearAll}>
                        Clear All
                    </button>
                </div>

                <section className="filter-groups" aria-label="Access need groups">
                    {filterSections.map((section) => (
                        <article className="filter-group" key={section.title}>
                            <div className="filter-group__header">
                                <h2>{section.title}</h2>
                            </div>

                            <div className="filter-chip-grid">
                                {section.items.map((item) => (
                                    <button
                                        className={`filter-chip ui-chip ${selectedFilters.includes(item) ? "ui-chip--active" : ""}`}
                                        key={item}
                                        type="button"
                                        aria-pressed={selectedFilters.includes(item)}
                                        onClick={() => toggleFilter(item)}
                                    >
                                        <span>{item}</span>
                                        <span aria-hidden="true">{selectedFilters.includes(item) ? "✓" : "+"}</span>
                                    </button>
                                ))}
                            </div>
                        </article>
                    ))}
                </section>

                <div className="filter-page__bottom-row">
                    <button className="primary-action ui-pill-button ui-pill-button--primary" type="button">
                        Request New Access Filter
                    </button>
                    <button
                        className="apply-filters-btn ui-pill-button"
                        type="button"
                        onClick={() => { saveFilters(selectedFilters); navigate(-1) }}
                    >
                        Apply Filters
                    </button>
                </div>
            </main>

            <Footer />
        </div>
    )
}

export default FilterPage
